port = 8000

[[routes]]
location = "/"
source = "/home/user/website/index.html"

[[routes]]
location = "/home"
source = "/home/user/website"

[[routes]]
location = "/image"
source = "/home/user/website/image.jpg"
